 version: '3'
 
 services:
  selenium-hub:
    image: selenium/hub:4.29.0-20250303
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - grid

  chrome:
    image: selenium/node-chrome:4.29.0-20250303
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
    networks:
      - grid

  firefox:
    image: selenium/node-firefox:4.29.0-20250303
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
    networks:
      - grid
    
 networks:
  grid:
    driver: bridge